site_name: chatbox
site_description: 

repo_url: https://github.com/nrsmac/chatbox
repo_name: nrsmac/chatbox

theme:
    name: material
    icon:
        logo: material/library
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: deep purple
          accent: pink
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: deep purple
          accent: pink
          toggle:
            icon: material/brightness-4
            name: Switch to light mode

markdown_extensions:
    - toc:
        permalink: true
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

plugins:
    - search
    - mkdocstrings:
        handlers:
            python:
                import:
                    - https://docs.python.org/3.11/objects.inv
                options:
                    docstring_style: google

watch:
    - docs
    - chatbox

nav:
    - About: index.md
    - Reference:
        - chatbox: reference/chatbox.md
